# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# west build -d build/cl_studio -b nice_nano_v2 -S studio-rpc-usb-uart -- -DSHIELD=corne_left -DCONFIG_ZMK_STUDIO=y
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: hshs52_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: hshs52_right nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  # - board: nice_nano_v2
  #   shield: hshs46_left nice_view_adapter nice_view
  # - board: nice_nano_v2
  #   shield: hshs46_right nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: settings_reset
